sudo: required

service:
  - docker

before_install:
  - docker build -t milanjain2189/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true milanjain2189/docker-react npm run test -- --coverage

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-700525971595"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY